name: Build Firmware

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get install -y unrar

      - name: Download
        run: curl -L --progress-bar -o firmware.rar "https://pixeldrain.com/api/file/nhdgcMa6?download"

      - name: Extract
        run: |
          unrar x firmware.rar
          rm firmware.rar
          ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scatter-files
          path: MT*_Android_scatter.*
